var m1 = require('./cloud/deleteStudent.js');
var m2 = require('./cloud/doesEmailExist.js');
var m3 = require('./cloud/userCount.js');
var m4 = require('./cloud/deleteChallenge.js');
var m5 = require('./cloud/testPush.js');
var m6 = require('./cloud/deletePinnedObjects.js');
var m7 = require('./cloud/changeUserId.js');
var m8 = require('./cloud/deleteStudentV2.js');
var m9 = require('./cloud/incrementCatAndSubStats.js'); //deprecated
var m10 = require('./cloud/deleteOldBlockStats.js');
var m11 = require('./cloud/questionCount.js');
var m12 = require('./cloud/chooseRandomQuestionsV2.js');
var m13 = require('./cloud/deleteTestQuestions.js');
var m14 = require('./cloud/studentRequestToTutor');
var m15 = require('./cloud/removeStudent');
var m16 = require('./cloud/addStudent');
var m17 = require('./cloud/deleteAllObjectsFromClasses');
var m18 = require('./cloud/sendMessageNotification.js');
var m19 = require('./cloud/deleteAnalytics.js');
var m20 = require('./cloud/sendYourTurnNotification.js');
var m21 = require('./cloud/getRandomOpponent.js');
var m22 = require('./cloud/sendTutorRequestNotification.js');
var m23 = require('./cloud/Response.js');
var m24 = require('./cloud/QuestionReport.js');
var m25 = require('./cloud/analyticsAfterSaves.js');
var m26 = require('./cloud/PublicUserData.js');

var l1 = require('./cloud/getAllSubStats.js');
var l2 = require('./cloud/getSubStats.js');
var l3 = require('./cloud/getSomeCatStats.js');
var l4 = require('./cloud/tutorRequestToStudent.js');
var l5 = require('./cloud/addTutor.js');
var l6 = require('./cloud/removeTutor.js');
var l7 = require('./cloud/chooseTenQuestions.js');
var l8 = require('./cloud/getStudentAllTimeAnswered.js');
var l9 = require('./cloud/queryAllQuestions.js');
var l10 = require('./cloud/oldestPendingQuestion.js');
var l11 = require('./cloud/tutorAlreadyRequestedStudent.js');
var l12 = require('./cloud/questionsByTutor.js');
var l13 = require('./cloud/assignedQuestionsToStudent.js');
var l14 = require('./cloud/oldestReportedQuestion.js');

var a1 = require('./cloud/assignQuestion.js');

